set search_path to cust;

create table Cust_behavior(
	customer_id int,
	age	int,
	gender	varchar(10),
	item_purchased	varchar(50),
	category varchar(50),
	purchase_amount	int,
	location varchar(50),
	size varchar(50),
	color varchar(25),
	season	varchar(25),
	review_rating	float,
	subscription_status	varchar(20),
	shipping_type	varchar(20),
	discount_applied	varchar(20),
	previous_purchases	int,
	payment_method	varchar(25),
	frequency_of_purchases	varchar(25),
	age_group	varchar(25),
	purchase_frequency_days int
);

select * from cust_behavior;

select count(*) from cust_behavior;

select distinct location from cust_behavior;

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as Total_Revenue
from Cust_behavior
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount
from cust_behavior
where discount_applied='Yes' and 
purchase_amount>=(select avg(purchase_amount ) from cust_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating::numeric),2) as avg_rating
from cust_behavior
group by item_purchased 
order by avg_rating desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, Round(avg(purchase_amount),2) as avg_amount
from cust_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
		count(customer_id) as total_customer,
		round(avg(purchase_amount),2) as avg_amount_spend,
		round(sum(purchase_amount),2) as total_revenue
from cust_behavior
group by subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
		round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_percent	
from cust_behavior
group by item_purchased
order by discount_percent desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with cte as (
		select customer_id,previous_purchases,
				case when previous_purchases=1 then 'New'
					 when previous_purchases between 2 and 10 then 'Returning'
					 else 'Loyal'
				End as customer_segment	 
		from cust_behavior
		)
select customer_segment,count(*) as customer_count
from cte
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 


with item_counts as (
	select 
		item_purchased,category,
		count(*) as total_orders,
		row_number() over(partition by category order by item_purchased) as item_rank
	from cust_behavior
	group by item_purchased,category
)
select item_rank,category,item_purchased,total_orders
from item_counts 
where item_rank<=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
	count(customer_id) as repeat_customers
from cust_behavior
where previous_purchases>5
group by subscription_status;

--Q10. What is the revenue contribution of each age group? 

select age_group ,
	   sum(purchase_amount) as revenue
from cust_behavior
group by age_group;

-----count of item for each category
select distinct category ,count(item_purchased) as total_items
from cust_behavior 
group by category
	   

---Which locations are buying the most items and generating the highest revenue?

select location,
		count(item_purchased) as items,
		sum(purchase_amount) as revenue
from cust_behavior
group by location
order by revenue desc;

















